services:
  - type: web
    name: FerreteriaLa32
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    branch: main
    envVars:
      - key: FLASK_APP
        value: Proyecto.py
